import ConnectKitButton from '@/components/ConnectButton';
import { Web3Provider } from '@/providers/Web3Provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
  props: any;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <header>
            <h1>Wonderland Challenge</h1>
            <ConnectKitButton />
          </header>
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
